version: '3.9'
services:
    obot-platform:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
          - .env
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        ports:
            - '8285:8080'
        container_name: obot
        restart: unless-stopped
